### ISSUE TITLE
CHATLOG and PLAYERINFO (Korean 2.45)

### ISSUE THREAD

**Issue by Minoost** [Icehunter/sharlayan#3]
https://github.com/Minoost/ffxivapp-memory/issues/1
Chatlog, PlayerInfo does not work w/ Korean 2.45 due to lack of PLAYERINFO and CHATLOG signatures.

https://github.com/Icehunter/ffxivapp/blob/4adf758eebfc2feef6e23d4000a4181d09a12ce4/FFXIVAPP.Client/Memory/PlayerInfoWorker.cs#L182
https://github.com/Icehunter/ffxivapp/blob/4adf758eebfc2feef6e23d4000a4181d09a12ce4/FFXIVAPP.Client/Memory/ChatLogWorker.cs#L176
Still have a no idea about "how can I port this thing" so I'd just leave it here

**Comment by Icehunter** [comment]
Sorry for the late reply... basically for the Chinese and Korean versions you have to look back in the NA/JA release history and find out when we got that patch; then go back in my commit history around that time. For this far back it's most likely in the icehunter/ffxivapp repo instead because this library was part of it back then. 

Once found you can take those offsets and data structures and copy them in.
